---
version: '3'
services:
  rest-proxy:
    image: confluentinc/cp-kafka-rest:${CONF_VER}
    ports:
      - 8082:8082
    hostname: rest-proxy
    depends_on:
      - kafka
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081


  schema_registry_ui:
    image: 'landoop/schema-registry-ui'
    hostname: schema_registry_ui
    depends_on:
      - schema-registry
    ports:
      - "8002:8000"
    environment:
      TZ: Australia/Sydney
      KAFKA_REST_PROXY_URL: "http://rest-proxy:8082"
      SCHEMAREGISTRY_URL: 'http://schema-registry:8081'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      PROXY: "true"
      PROXY_SKIP_VERIFY: "true"
      MAX_BYTES: "20000000"
    extra_hosts:
      - "moby:127.0.0.1"

  kafka_topics_ui:
    image: 'landoop/kafka-topics-ui:0.9.4'
    hostname: kafka_topics_ui
    depends_on:
      - kafka
    ports:
      - "8001:8000"
    environment:
      TZ: Australia/Sydney
      KAFKA_REST_PROXY_URL: "http://rest-proxy:8082"
      PROXY: "true"
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-connect-ui:
    image: 'landoop/kafka-connect-ui'
    hostname: kafka-connect-ui
    depends_on:
      - kafka-connect
    ports:
      - "8003:8000"
    environment:
      TZ: Australia/Sydney
      CONNECT_URL: "http://kafka-connect:8083"
    extra_hosts:
      - "moby:127.0.0.1"

